(define (problem agendamento-otimizado)
    (:domain agendamento-universitario-simples)
    (:objects
        lei liacd ldm - curso
        ano1 ano2 ano3 - ano
        seg_m seg_t ter_m ter_t qua_m qua_t qui_m qui_t sex_m sex_t - slot
        Auditorio1 Auditorio2 Auditorio3 Sala_B1 Sala_B2 Sala_B3 Sala_C1 Sala_C2 Sala_C3 - sala
        LEI_1_ExameA LEI_1_ExameB LEI_1_ExameC LEI_1_ExameD LEI_1_ExameE LEI_2_ExameA LEI_2_ExameB LEI_2_ExameC LEI_2_ExameD LEI_2_ExameE LEI_3_ExameA LEI_3_ExameB LEI_3_ExameC LEI_3_ExameD LEI_3_ExameE LIACD_1_ExameA LIACD_1_ExameB LIACD_1_ExameC LIACD_1_ExameD LIACD_1_ExameE LIACD_2_ExameA LIACD_2_ExameB LIACD_2_ExameC LIACD_2_ExameD LIACD_2_ExameE LIACD_3_ExameA LIACD_3_ExameB LIACD_3_ExameC LIACD_3_ExameD LIACD_3_ExameE LDM_1_ExameA LDM_1_ExameB LDM_1_ExameC LDM_1_ExameD LDM_1_ExameE LDM_2_ExameA LDM_2_ExameB LDM_2_ExameC LDM_2_ExameD LDM_2_ExameE LDM_3_ExameA LDM_3_ExameB LDM_3_ExameC LDM_3_ExameD LDM_3_ExameE - exame
    )
    (:init
        (do_curso LEI_1_ExameA lei) (do_ano LEI_1_ExameA ano1)
        (exame_pendente LEI_1_ExameA)
        (cabe_na_sala LEI_1_ExameA Auditorio1)
        (cabe_na_sala LEI_1_ExameA Auditorio2)
        (cabe_na_sala LEI_1_ExameA Auditorio3)
        (do_curso LEI_1_ExameB lei) (do_ano LEI_1_ExameB ano1)
        (exame_pendente LEI_1_ExameB)
        (cabe_na_sala LEI_1_ExameB Auditorio1)
        (cabe_na_sala LEI_1_ExameB Auditorio2)
        (cabe_na_sala LEI_1_ExameB Auditorio3)
        (do_curso LEI_1_ExameC lei) (do_ano LEI_1_ExameC ano1)
        (exame_pendente LEI_1_ExameC)
        (cabe_na_sala LEI_1_ExameC Auditorio1)
        (cabe_na_sala LEI_1_ExameC Auditorio2)
        (cabe_na_sala LEI_1_ExameC Auditorio3)
        (do_curso LEI_1_ExameD lei) (do_ano LEI_1_ExameD ano1)
        (exame_pendente LEI_1_ExameD)
        (cabe_na_sala LEI_1_ExameD Auditorio1)
        (cabe_na_sala LEI_1_ExameD Auditorio2)
        (cabe_na_sala LEI_1_ExameD Auditorio3)
        (do_curso LEI_1_ExameE lei) (do_ano LEI_1_ExameE ano1)
        (exame_pendente LEI_1_ExameE)
        (cabe_na_sala LEI_1_ExameE Auditorio1)
        (cabe_na_sala LEI_1_ExameE Auditorio2)
        (cabe_na_sala LEI_1_ExameE Auditorio3)
        (do_curso LEI_2_ExameA lei) (do_ano LEI_2_ExameA ano2)
        (exame_pendente LEI_2_ExameA)
        (cabe_na_sala LEI_2_ExameA Auditorio1)
        (cabe_na_sala LEI_2_ExameA Auditorio2)
        (cabe_na_sala LEI_2_ExameA Auditorio3)
        (do_curso LEI_2_ExameB lei) (do_ano LEI_2_ExameB ano2)
        (exame_pendente LEI_2_ExameB)
        (cabe_na_sala LEI_2_ExameB Auditorio1)
        (cabe_na_sala LEI_2_ExameB Auditorio2)
        (cabe_na_sala LEI_2_ExameB Auditorio3)
        (do_curso LEI_2_ExameC lei) (do_ano LEI_2_ExameC ano2)
        (exame_pendente LEI_2_ExameC)
        (cabe_na_sala LEI_2_ExameC Auditorio1)
        (cabe_na_sala LEI_2_ExameC Auditorio2)
        (cabe_na_sala LEI_2_ExameC Auditorio3)
        (do_curso LEI_2_ExameD lei) (do_ano LEI_2_ExameD ano2)
        (exame_pendente LEI_2_ExameD)
        (cabe_na_sala LEI_2_ExameD Auditorio1)
        (cabe_na_sala LEI_2_ExameD Auditorio2)
        (cabe_na_sala LEI_2_ExameD Auditorio3)
        (do_curso LEI_2_ExameE lei) (do_ano LEI_2_ExameE ano2)
        (exame_pendente LEI_2_ExameE)
        (cabe_na_sala LEI_2_ExameE Auditorio1)
        (cabe_na_sala LEI_2_ExameE Auditorio2)
        (cabe_na_sala LEI_2_ExameE Auditorio3)
        (do_curso LEI_3_ExameA lei) (do_ano LEI_3_ExameA ano3)
        (exame_pendente LEI_3_ExameA)
        (cabe_na_sala LEI_3_ExameA Auditorio1)
        (cabe_na_sala LEI_3_ExameA Auditorio2)
        (cabe_na_sala LEI_3_ExameA Auditorio3)
        (do_curso LEI_3_ExameB lei) (do_ano LEI_3_ExameB ano3)
        (exame_pendente LEI_3_ExameB)
        (cabe_na_sala LEI_3_ExameB Auditorio1)
        (cabe_na_sala LEI_3_ExameB Auditorio2)
        (cabe_na_sala LEI_3_ExameB Auditorio3)
        (do_curso LEI_3_ExameC lei) (do_ano LEI_3_ExameC ano3)
        (exame_pendente LEI_3_ExameC)
        (cabe_na_sala LEI_3_ExameC Auditorio1)
        (cabe_na_sala LEI_3_ExameC Auditorio2)
        (cabe_na_sala LEI_3_ExameC Auditorio3)
        (do_curso LEI_3_ExameD lei) (do_ano LEI_3_ExameD ano3)
        (exame_pendente LEI_3_ExameD)
        (cabe_na_sala LEI_3_ExameD Auditorio1)
        (cabe_na_sala LEI_3_ExameD Auditorio2)
        (cabe_na_sala LEI_3_ExameD Auditorio3)
        (do_curso LEI_3_ExameE lei) (do_ano LEI_3_ExameE ano3)
        (exame_pendente LEI_3_ExameE)
        (cabe_na_sala LEI_3_ExameE Auditorio1)
        (cabe_na_sala LEI_3_ExameE Auditorio2)
        (cabe_na_sala LEI_3_ExameE Auditorio3)
        (do_curso LIACD_1_ExameA liacd) (do_ano LIACD_1_ExameA ano1)
        (exame_pendente LIACD_1_ExameA)
        (cabe_na_sala LIACD_1_ExameA Sala_B1)
        (cabe_na_sala LIACD_1_ExameA Sala_B2)
        (cabe_na_sala LIACD_1_ExameA Sala_B3)
        (do_curso LIACD_1_ExameB liacd) (do_ano LIACD_1_ExameB ano1)
        (exame_pendente LIACD_1_ExameB)
        (cabe_na_sala LIACD_1_ExameB Sala_B1)
        (cabe_na_sala LIACD_1_ExameB Sala_B2)
        (cabe_na_sala LIACD_1_ExameB Sala_B3)
        (do_curso LIACD_1_ExameC liacd) (do_ano LIACD_1_ExameC ano1)
        (exame_pendente LIACD_1_ExameC)
        (cabe_na_sala LIACD_1_ExameC Sala_B1)
        (cabe_na_sala LIACD_1_ExameC Sala_B2)
        (cabe_na_sala LIACD_1_ExameC Sala_B3)
        (do_curso LIACD_1_ExameD liacd) (do_ano LIACD_1_ExameD ano1)
        (exame_pendente LIACD_1_ExameD)
        (cabe_na_sala LIACD_1_ExameD Sala_B1)
        (cabe_na_sala LIACD_1_ExameD Sala_B2)
        (cabe_na_sala LIACD_1_ExameD Sala_B3)
        (do_curso LIACD_1_ExameE liacd) (do_ano LIACD_1_ExameE ano1)
        (exame_pendente LIACD_1_ExameE)
        (cabe_na_sala LIACD_1_ExameE Sala_B1)
        (cabe_na_sala LIACD_1_ExameE Sala_B2)
        (cabe_na_sala LIACD_1_ExameE Sala_B3)
        (do_curso LIACD_2_ExameA liacd) (do_ano LIACD_2_ExameA ano2)
        (exame_pendente LIACD_2_ExameA)
        (cabe_na_sala LIACD_2_ExameA Sala_B1)
        (cabe_na_sala LIACD_2_ExameA Sala_B2)
        (cabe_na_sala LIACD_2_ExameA Sala_B3)
        (do_curso LIACD_2_ExameB liacd) (do_ano LIACD_2_ExameB ano2)
        (exame_pendente LIACD_2_ExameB)
        (cabe_na_sala LIACD_2_ExameB Sala_B1)
        (cabe_na_sala LIACD_2_ExameB Sala_B2)
        (cabe_na_sala LIACD_2_ExameB Sala_B3)
        (do_curso LIACD_2_ExameC liacd) (do_ano LIACD_2_ExameC ano2)
        (exame_pendente LIACD_2_ExameC)
        (cabe_na_sala LIACD_2_ExameC Sala_B1)
        (cabe_na_sala LIACD_2_ExameC Sala_B2)
        (cabe_na_sala LIACD_2_ExameC Sala_B3)
        (do_curso LIACD_2_ExameD liacd) (do_ano LIACD_2_ExameD ano2)
        (exame_pendente LIACD_2_ExameD)
        (cabe_na_sala LIACD_2_ExameD Sala_B1)
        (cabe_na_sala LIACD_2_ExameD Sala_B2)
        (cabe_na_sala LIACD_2_ExameD Sala_B3)
        (do_curso LIACD_2_ExameE liacd) (do_ano LIACD_2_ExameE ano2)
        (exame_pendente LIACD_2_ExameE)
        (cabe_na_sala LIACD_2_ExameE Sala_B1)
        (cabe_na_sala LIACD_2_ExameE Sala_B2)
        (cabe_na_sala LIACD_2_ExameE Sala_B3)
        (do_curso LIACD_3_ExameA liacd) (do_ano LIACD_3_ExameA ano3)
        (exame_pendente LIACD_3_ExameA)
        (cabe_na_sala LIACD_3_ExameA Sala_B1)
        (cabe_na_sala LIACD_3_ExameA Sala_B2)
        (cabe_na_sala LIACD_3_ExameA Sala_B3)
        (do_curso LIACD_3_ExameB liacd) (do_ano LIACD_3_ExameB ano3)
        (exame_pendente LIACD_3_ExameB)
        (cabe_na_sala LIACD_3_ExameB Sala_B1)
        (cabe_na_sala LIACD_3_ExameB Sala_B2)
        (cabe_na_sala LIACD_3_ExameB Sala_B3)
        (do_curso LIACD_3_ExameC liacd) (do_ano LIACD_3_ExameC ano3)
        (exame_pendente LIACD_3_ExameC)
        (cabe_na_sala LIACD_3_ExameC Sala_B1)
        (cabe_na_sala LIACD_3_ExameC Sala_B2)
        (cabe_na_sala LIACD_3_ExameC Sala_B3)
        (do_curso LIACD_3_ExameD liacd) (do_ano LIACD_3_ExameD ano3)
        (exame_pendente LIACD_3_ExameD)
        (cabe_na_sala LIACD_3_ExameD Sala_B1)
        (cabe_na_sala LIACD_3_ExameD Sala_B2)
        (cabe_na_sala LIACD_3_ExameD Sala_B3)
        (do_curso LIACD_3_ExameE liacd) (do_ano LIACD_3_ExameE ano3)
        (exame_pendente LIACD_3_ExameE)
        (cabe_na_sala LIACD_3_ExameE Sala_B1)
        (cabe_na_sala LIACD_3_ExameE Sala_B2)
        (cabe_na_sala LIACD_3_ExameE Sala_B3)
        (do_curso LDM_1_ExameA ldm) (do_ano LDM_1_ExameA ano1)
        (exame_pendente LDM_1_ExameA)
        (cabe_na_sala LDM_1_ExameA Sala_C1)
        (cabe_na_sala LDM_1_ExameA Sala_C2)
        (cabe_na_sala LDM_1_ExameA Sala_C3)
        (do_curso LDM_1_ExameB ldm) (do_ano LDM_1_ExameB ano1)
        (exame_pendente LDM_1_ExameB)
        (cabe_na_sala LDM_1_ExameB Sala_C1)
        (cabe_na_sala LDM_1_ExameB Sala_C2)
        (cabe_na_sala LDM_1_ExameB Sala_C3)
        (do_curso LDM_1_ExameC ldm) (do_ano LDM_1_ExameC ano1)
        (exame_pendente LDM_1_ExameC)
        (cabe_na_sala LDM_1_ExameC Sala_C1)
        (cabe_na_sala LDM_1_ExameC Sala_C2)
        (cabe_na_sala LDM_1_ExameC Sala_C3)
        (do_curso LDM_1_ExameD ldm) (do_ano LDM_1_ExameD ano1)
        (exame_pendente LDM_1_ExameD)
        (cabe_na_sala LDM_1_ExameD Sala_C1)
        (cabe_na_sala LDM_1_ExameD Sala_C2)
        (cabe_na_sala LDM_1_ExameD Sala_C3)
        (do_curso LDM_1_ExameE ldm) (do_ano LDM_1_ExameE ano1)
        (exame_pendente LDM_1_ExameE)
        (cabe_na_sala LDM_1_ExameE Sala_C1)
        (cabe_na_sala LDM_1_ExameE Sala_C2)
        (cabe_na_sala LDM_1_ExameE Sala_C3)
        (do_curso LDM_2_ExameA ldm) (do_ano LDM_2_ExameA ano2)
        (exame_pendente LDM_2_ExameA)
        (cabe_na_sala LDM_2_ExameA Sala_C1)
        (cabe_na_sala LDM_2_ExameA Sala_C2)
        (cabe_na_sala LDM_2_ExameA Sala_C3)
        (do_curso LDM_2_ExameB ldm) (do_ano LDM_2_ExameB ano2)
        (exame_pendente LDM_2_ExameB)
        (cabe_na_sala LDM_2_ExameB Sala_C1)
        (cabe_na_sala LDM_2_ExameB Sala_C2)
        (cabe_na_sala LDM_2_ExameB Sala_C3)
        (do_curso LDM_2_ExameC ldm) (do_ano LDM_2_ExameC ano2)
        (exame_pendente LDM_2_ExameC)
        (cabe_na_sala LDM_2_ExameC Sala_C1)
        (cabe_na_sala LDM_2_ExameC Sala_C2)
        (cabe_na_sala LDM_2_ExameC Sala_C3)
        (do_curso LDM_2_ExameD ldm) (do_ano LDM_2_ExameD ano2)
        (exame_pendente LDM_2_ExameD)
        (cabe_na_sala LDM_2_ExameD Sala_C1)
        (cabe_na_sala LDM_2_ExameD Sala_C2)
        (cabe_na_sala LDM_2_ExameD Sala_C3)
        (do_curso LDM_2_ExameE ldm) (do_ano LDM_2_ExameE ano2)
        (exame_pendente LDM_2_ExameE)
        (cabe_na_sala LDM_2_ExameE Sala_C1)
        (cabe_na_sala LDM_2_ExameE Sala_C2)
        (cabe_na_sala LDM_2_ExameE Sala_C3)
        (do_curso LDM_3_ExameA ldm) (do_ano LDM_3_ExameA ano3)
        (exame_pendente LDM_3_ExameA)
        (cabe_na_sala LDM_3_ExameA Sala_C1)
        (cabe_na_sala LDM_3_ExameA Sala_C2)
        (cabe_na_sala LDM_3_ExameA Sala_C3)
        (do_curso LDM_3_ExameB ldm) (do_ano LDM_3_ExameB ano3)
        (exame_pendente LDM_3_ExameB)
        (cabe_na_sala LDM_3_ExameB Sala_C1)
        (cabe_na_sala LDM_3_ExameB Sala_C2)
        (cabe_na_sala LDM_3_ExameB Sala_C3)
        (do_curso LDM_3_ExameC ldm) (do_ano LDM_3_ExameC ano3)
        (exame_pendente LDM_3_ExameC)
        (cabe_na_sala LDM_3_ExameC Sala_C1)
        (cabe_na_sala LDM_3_ExameC Sala_C2)
        (cabe_na_sala LDM_3_ExameC Sala_C3)
        (do_curso LDM_3_ExameD ldm) (do_ano LDM_3_ExameD ano3)
        (exame_pendente LDM_3_ExameD)
        (cabe_na_sala LDM_3_ExameD Sala_C1)
        (cabe_na_sala LDM_3_ExameD Sala_C2)
        (cabe_na_sala LDM_3_ExameD Sala_C3)
        (do_curso LDM_3_ExameE ldm) (do_ano LDM_3_ExameE ano3)
        (exame_pendente LDM_3_ExameE)
        (cabe_na_sala LDM_3_ExameE Sala_C1)
        (cabe_na_sala LDM_3_ExameE Sala_C2)
        (cabe_na_sala LDM_3_ExameE Sala_C3)
        (sala_livre Auditorio1 seg_m)
        (sala_livre Auditorio1 seg_t)
        (sala_livre Auditorio1 ter_m)
        (sala_livre Auditorio1 ter_t)
        (sala_livre Auditorio1 qua_m)
        (sala_livre Auditorio1 qua_t)
        (sala_livre Auditorio1 qui_m)
        (sala_livre Auditorio1 qui_t)
        (sala_livre Auditorio1 sex_m)
        (sala_livre Auditorio1 sex_t)
        (sala_livre Auditorio2 seg_m)
        (sala_livre Auditorio2 seg_t)
        (sala_livre Auditorio2 ter_m)
        (sala_livre Auditorio2 ter_t)
        (sala_livre Auditorio2 qua_m)
        (sala_livre Auditorio2 qua_t)
        (sala_livre Auditorio2 qui_m)
        (sala_livre Auditorio2 qui_t)
        (sala_livre Auditorio2 sex_m)
        (sala_livre Auditorio2 sex_t)
        (sala_livre Auditorio3 seg_m)
        (sala_livre Auditorio3 seg_t)
        (sala_livre Auditorio3 ter_m)
        (sala_livre Auditorio3 ter_t)
        (sala_livre Auditorio3 qua_m)
        (sala_livre Auditorio3 qua_t)
        (sala_livre Auditorio3 qui_m)
        (sala_livre Auditorio3 qui_t)
        (sala_livre Auditorio3 sex_m)
        (sala_livre Auditorio3 sex_t)
        (sala_livre Sala_B1 seg_m)
        (sala_livre Sala_B1 seg_t)
        (sala_livre Sala_B1 ter_m)
        (sala_livre Sala_B1 ter_t)
        (sala_livre Sala_B1 qua_m)
        (sala_livre Sala_B1 qua_t)
        (sala_livre Sala_B1 qui_m)
        (sala_livre Sala_B1 qui_t)
        (sala_livre Sala_B1 sex_m)
        (sala_livre Sala_B1 sex_t)
        (sala_livre Sala_B2 seg_m)
        (sala_livre Sala_B2 seg_t)
        (sala_livre Sala_B2 ter_m)
        (sala_livre Sala_B2 ter_t)
        (sala_livre Sala_B2 qua_m)
        (sala_livre Sala_B2 qua_t)
        (sala_livre Sala_B2 qui_m)
        (sala_livre Sala_B2 qui_t)
        (sala_livre Sala_B2 sex_m)
        (sala_livre Sala_B2 sex_t)
        (sala_livre Sala_B3 seg_m)
        (sala_livre Sala_B3 seg_t)
        (sala_livre Sala_B3 ter_m)
        (sala_livre Sala_B3 ter_t)
        (sala_livre Sala_B3 qua_m)
        (sala_livre Sala_B3 qua_t)
        (sala_livre Sala_B3 qui_m)
        (sala_livre Sala_B3 qui_t)
        (sala_livre Sala_B3 sex_m)
        (sala_livre Sala_B3 sex_t)
        (sala_livre Sala_C1 seg_m)
        (sala_livre Sala_C1 seg_t)
        (sala_livre Sala_C1 ter_m)
        (sala_livre Sala_C1 ter_t)
        (sala_livre Sala_C1 qua_m)
        (sala_livre Sala_C1 qua_t)
        (sala_livre Sala_C1 qui_m)
        (sala_livre Sala_C1 qui_t)
        (sala_livre Sala_C1 sex_m)
        (sala_livre Sala_C1 sex_t)
        (sala_livre Sala_C2 seg_m)
        (sala_livre Sala_C2 seg_t)
        (sala_livre Sala_C2 ter_m)
        (sala_livre Sala_C2 ter_t)
        (sala_livre Sala_C2 qua_m)
        (sala_livre Sala_C2 qua_t)
        (sala_livre Sala_C2 qui_m)
        (sala_livre Sala_C2 qui_t)
        (sala_livre Sala_C2 sex_m)
        (sala_livre Sala_C2 sex_t)
        (sala_livre Sala_C3 seg_m)
        (sala_livre Sala_C3 seg_t)
        (sala_livre Sala_C3 ter_m)
        (sala_livre Sala_C3 ter_t)
        (sala_livre Sala_C3 qua_m)
        (sala_livre Sala_C3 qua_t)
        (sala_livre Sala_C3 qui_m)
        (sala_livre Sala_C3 qui_t)
        (sala_livre Sala_C3 sex_m)
        (sala_livre Sala_C3 sex_t)
        (curso_ano_sem_conflito lei ano1 seg_m)
        (curso_ano_sem_conflito lei ano1 seg_t)
        (curso_ano_sem_conflito lei ano1 ter_m)
        (curso_ano_sem_conflito lei ano1 ter_t)
        (curso_ano_sem_conflito lei ano1 qua_m)
        (curso_ano_sem_conflito lei ano1 qua_t)
        (curso_ano_sem_conflito lei ano1 qui_m)
        (curso_ano_sem_conflito lei ano1 qui_t)
        (curso_ano_sem_conflito lei ano1 sex_m)
        (curso_ano_sem_conflito lei ano1 sex_t)
        (curso_ano_sem_conflito lei ano2 seg_m)
        (curso_ano_sem_conflito lei ano2 seg_t)
        (curso_ano_sem_conflito lei ano2 ter_m)
        (curso_ano_sem_conflito lei ano2 ter_t)
        (curso_ano_sem_conflito lei ano2 qua_m)
        (curso_ano_sem_conflito lei ano2 qua_t)
        (curso_ano_sem_conflito lei ano2 qui_m)
        (curso_ano_sem_conflito lei ano2 qui_t)
        (curso_ano_sem_conflito lei ano2 sex_m)
        (curso_ano_sem_conflito lei ano2 sex_t)
        (curso_ano_sem_conflito lei ano3 seg_m)
        (curso_ano_sem_conflito lei ano3 seg_t)
        (curso_ano_sem_conflito lei ano3 ter_m)
        (curso_ano_sem_conflito lei ano3 ter_t)
        (curso_ano_sem_conflito lei ano3 qua_m)
        (curso_ano_sem_conflito lei ano3 qua_t)
        (curso_ano_sem_conflito lei ano3 qui_m)
        (curso_ano_sem_conflito lei ano3 qui_t)
        (curso_ano_sem_conflito lei ano3 sex_m)
        (curso_ano_sem_conflito lei ano3 sex_t)
        (curso_ano_sem_conflito liacd ano1 seg_m)
        (curso_ano_sem_conflito liacd ano1 seg_t)
        (curso_ano_sem_conflito liacd ano1 ter_m)
        (curso_ano_sem_conflito liacd ano1 ter_t)
        (curso_ano_sem_conflito liacd ano1 qua_m)
        (curso_ano_sem_conflito liacd ano1 qua_t)
        (curso_ano_sem_conflito liacd ano1 qui_m)
        (curso_ano_sem_conflito liacd ano1 qui_t)
        (curso_ano_sem_conflito liacd ano1 sex_m)
        (curso_ano_sem_conflito liacd ano1 sex_t)
        (curso_ano_sem_conflito liacd ano2 seg_m)
        (curso_ano_sem_conflito liacd ano2 seg_t)
        (curso_ano_sem_conflito liacd ano2 ter_m)
        (curso_ano_sem_conflito liacd ano2 ter_t)
        (curso_ano_sem_conflito liacd ano2 qua_m)
        (curso_ano_sem_conflito liacd ano2 qua_t)
        (curso_ano_sem_conflito liacd ano2 qui_m)
        (curso_ano_sem_conflito liacd ano2 qui_t)
        (curso_ano_sem_conflito liacd ano2 sex_m)
        (curso_ano_sem_conflito liacd ano2 sex_t)
        (curso_ano_sem_conflito liacd ano3 seg_m)
        (curso_ano_sem_conflito liacd ano3 seg_t)
        (curso_ano_sem_conflito liacd ano3 ter_m)
        (curso_ano_sem_conflito liacd ano3 ter_t)
        (curso_ano_sem_conflito liacd ano3 qua_m)
        (curso_ano_sem_conflito liacd ano3 qua_t)
        (curso_ano_sem_conflito liacd ano3 qui_m)
        (curso_ano_sem_conflito liacd ano3 qui_t)
        (curso_ano_sem_conflito liacd ano3 sex_m)
        (curso_ano_sem_conflito liacd ano3 sex_t)
        (curso_ano_sem_conflito ldm ano1 seg_m)
        (curso_ano_sem_conflito ldm ano1 seg_t)
        (curso_ano_sem_conflito ldm ano1 ter_m)
        (curso_ano_sem_conflito ldm ano1 ter_t)
        (curso_ano_sem_conflito ldm ano1 qua_m)
        (curso_ano_sem_conflito ldm ano1 qua_t)
        (curso_ano_sem_conflito ldm ano1 qui_m)
        (curso_ano_sem_conflito ldm ano1 qui_t)
        (curso_ano_sem_conflito ldm ano1 sex_m)
        (curso_ano_sem_conflito ldm ano1 sex_t)
        (curso_ano_sem_conflito ldm ano2 seg_m)
        (curso_ano_sem_conflito ldm ano2 seg_t)
        (curso_ano_sem_conflito ldm ano2 ter_m)
        (curso_ano_sem_conflito ldm ano2 ter_t)
        (curso_ano_sem_conflito ldm ano2 qua_m)
        (curso_ano_sem_conflito ldm ano2 qua_t)
        (curso_ano_sem_conflito ldm ano2 qui_m)
        (curso_ano_sem_conflito ldm ano2 qui_t)
        (curso_ano_sem_conflito ldm ano2 sex_m)
        (curso_ano_sem_conflito ldm ano2 sex_t)
        (curso_ano_sem_conflito ldm ano3 seg_m)
        (curso_ano_sem_conflito ldm ano3 seg_t)
        (curso_ano_sem_conflito ldm ano3 ter_m)
        (curso_ano_sem_conflito ldm ano3 ter_t)
        (curso_ano_sem_conflito ldm ano3 qua_m)
        (curso_ano_sem_conflito ldm ano3 qua_t)
        (curso_ano_sem_conflito ldm ano3 qui_m)
        (curso_ano_sem_conflito ldm ano3 qui_t)
        (curso_ano_sem_conflito ldm ano3 sex_m)
        (curso_ano_sem_conflito ldm ano3 sex_t)
    )
    (:goal (and
        (agendado LEI_1_ExameA)
        (agendado LEI_1_ExameB)
        (agendado LEI_1_ExameC)
        (agendado LEI_1_ExameD)
        (agendado LEI_1_ExameE)
        (agendado LEI_2_ExameA)
        (agendado LEI_2_ExameB)
        (agendado LEI_2_ExameC)
        (agendado LEI_2_ExameD)
        (agendado LEI_2_ExameE)
        (agendado LEI_3_ExameA)
        (agendado LEI_3_ExameB)
        (agendado LEI_3_ExameC)
        (agendado LEI_3_ExameD)
        (agendado LEI_3_ExameE)
        (agendado LIACD_1_ExameA)
        (agendado LIACD_1_ExameB)
        (agendado LIACD_1_ExameC)
        (agendado LIACD_1_ExameD)
        (agendado LIACD_1_ExameE)
        (agendado LIACD_2_ExameA)
        (agendado LIACD_2_ExameB)
        (agendado LIACD_2_ExameC)
        (agendado LIACD_2_ExameD)
        (agendado LIACD_2_ExameE)
        (agendado LIACD_3_ExameA)
        (agendado LIACD_3_ExameB)
        (agendado LIACD_3_ExameC)
        (agendado LIACD_3_ExameD)
        (agendado LIACD_3_ExameE)
        (agendado LDM_1_ExameA)
        (agendado LDM_1_ExameB)
        (agendado LDM_1_ExameC)
        (agendado LDM_1_ExameD)
        (agendado LDM_1_ExameE)
        (agendado LDM_2_ExameA)
        (agendado LDM_2_ExameB)
        (agendado LDM_2_ExameC)
        (agendado LDM_2_ExameD)
        (agendado LDM_2_ExameE)
        (agendado LDM_3_ExameA)
        (agendado LDM_3_ExameB)
        (agendado LDM_3_ExameC)
        (agendado LDM_3_ExameD)
        (agendado LDM_3_ExameE)
    ))
)
