(define (problem semester-exams)
  (:domain exam-scheduling)
  (:objects
    exam-l-1 exam-l-2 exam-l-3 exam-l-4 exam-l-5 - large-exam
    exam-s-1 exam-s-2 exam-s-3 exam-s-4 exam-s-5 exam-s-6 exam-s-7 exam-s-8 exam-s-9 exam-s-10 - small-exam
    auditorium-a auditorium-b - large-room
    room-101 room-102 room-103 lab-c - small-room
    mon tue wed thu fri - day
    am pm - slot
  )

  (:init
    (unallocated exam-l-1)
    (unallocated exam-l-2)
    (unallocated exam-l-3)
    (unallocated exam-l-4)
    (unallocated exam-l-5)
    (unallocated exam-s-1)
    (unallocated exam-s-2)
    (unallocated exam-s-3)
    (unallocated exam-s-4)
    (unallocated exam-s-5)
    (unallocated exam-s-6)
    (unallocated exam-s-7)
    (unallocated exam-s-8)
    (unallocated exam-s-9)
    (unallocated exam-s-10)

    (room-free auditorium-a mon am)
    (room-free auditorium-a mon pm)
    (room-free auditorium-a tue am)
    (room-free auditorium-a tue pm)
    (room-free auditorium-a wed am)
    (room-free auditorium-a wed pm)
    (room-free auditorium-a thu am)
    (room-free auditorium-a thu pm)
    (room-free auditorium-a fri am)
    (room-free auditorium-a fri pm)
    (room-free auditorium-b mon am)
    (room-free auditorium-b mon pm)
    (room-free auditorium-b tue am)
    (room-free auditorium-b tue pm)
    (room-free auditorium-b wed am)
    (room-free auditorium-b wed pm)
    (room-free auditorium-b thu am)
    (room-free auditorium-b thu pm)
    (room-free auditorium-b fri am)
    (room-free auditorium-b fri pm)
    (room-free room-101 mon am)
    (room-free room-101 mon pm)
    (room-free room-101 tue am)
    (room-free room-101 tue pm)
    (room-free room-101 wed am)
    (room-free room-101 wed pm)
    (room-free room-101 thu am)
    (room-free room-101 thu pm)
    (room-free room-101 fri am)
    (room-free room-101 fri pm)
    (room-free room-102 mon am)
    (room-free room-102 mon pm)
    (room-free room-102 tue am)
    (room-free room-102 tue pm)
    (room-free room-102 wed am)
    (room-free room-102 wed pm)
    (room-free room-102 thu am)
    (room-free room-102 thu pm)
    (room-free room-102 fri am)
    (room-free room-102 fri pm)
    (room-free room-103 mon am)
    (room-free room-103 mon pm)
    (room-free room-103 tue am)
    (room-free room-103 tue pm)
    (room-free room-103 wed am)
    (room-free room-103 wed pm)
    (room-free room-103 thu am)
    (room-free room-103 thu pm)
    (room-free room-103 fri am)
    (room-free room-103 fri pm)
    (room-free lab-c mon am)
    (room-free lab-c mon pm)
    (room-free lab-c tue am)
    (room-free lab-c tue pm)
    (room-free lab-c wed am)
    (room-free lab-c wed pm)
    (room-free lab-c thu am)
    (room-free lab-c thu pm)
    (room-free lab-c fri am)
    (room-free lab-c fri pm)

    (fits-in exam-l-1 auditorium-a)
    (fits-in exam-l-2 auditorium-a)
    (fits-in exam-l-3 auditorium-a)
    (fits-in exam-l-4 auditorium-a)
    (fits-in exam-l-5 auditorium-a)
    (fits-in exam-s-1 auditorium-a)
    (fits-in exam-s-2 auditorium-a)
    (fits-in exam-s-3 auditorium-a)
    (fits-in exam-s-4 auditorium-a)
    (fits-in exam-s-5 auditorium-a)
    (fits-in exam-s-6 auditorium-a)
    (fits-in exam-s-7 auditorium-a)
    (fits-in exam-s-8 auditorium-a)
    (fits-in exam-s-9 auditorium-a)
    (fits-in exam-s-10 auditorium-a)
    (fits-in exam-l-1 auditorium-b)
    (fits-in exam-l-2 auditorium-b)
    (fits-in exam-l-3 auditorium-b)
    (fits-in exam-l-4 auditorium-b)
    (fits-in exam-l-5 auditorium-b)
    (fits-in exam-s-1 auditorium-b)
    (fits-in exam-s-2 auditorium-b)
    (fits-in exam-s-3 auditorium-b)
    (fits-in exam-s-4 auditorium-b)
    (fits-in exam-s-5 auditorium-b)
    (fits-in exam-s-6 auditorium-b)
    (fits-in exam-s-7 auditorium-b)
    (fits-in exam-s-8 auditorium-b)
    (fits-in exam-s-9 auditorium-b)
    (fits-in exam-s-10 auditorium-b)
    (fits-in exam-s-1 room-101)
    (fits-in exam-s-2 room-101)
    (fits-in exam-s-3 room-101)
    (fits-in exam-s-4 room-101)
    (fits-in exam-s-5 room-101)
    (fits-in exam-s-6 room-101)
    (fits-in exam-s-7 room-101)
    (fits-in exam-s-8 room-101)
    (fits-in exam-s-9 room-101)
    (fits-in exam-s-10 room-101)
    (fits-in exam-s-1 room-102)
    (fits-in exam-s-2 room-102)
    (fits-in exam-s-3 room-102)
    (fits-in exam-s-4 room-102)
    (fits-in exam-s-5 room-102)
    (fits-in exam-s-6 room-102)
    (fits-in exam-s-7 room-102)
    (fits-in exam-s-8 room-102)
    (fits-in exam-s-9 room-102)
    (fits-in exam-s-10 room-102)
    (fits-in exam-s-1 room-103)
    (fits-in exam-s-2 room-103)
    (fits-in exam-s-3 room-103)
    (fits-in exam-s-4 room-103)
    (fits-in exam-s-5 room-103)
    (fits-in exam-s-6 room-103)
    (fits-in exam-s-7 room-103)
    (fits-in exam-s-8 room-103)
    (fits-in exam-s-9 room-103)
    (fits-in exam-s-10 room-103)
    (fits-in exam-s-1 lab-c)
    (fits-in exam-s-2 lab-c)
    (fits-in exam-s-3 lab-c)
    (fits-in exam-s-4 lab-c)
    (fits-in exam-s-5 lab-c)
    (fits-in exam-s-6 lab-c)
    (fits-in exam-s-7 lab-c)
    (fits-in exam-s-8 lab-c)
    (fits-in exam-s-9 lab-c)
    (fits-in exam-s-10 lab-c)
  )

  (:goal
    (and
      (allocated exam-l-1)
      (allocated exam-l-2)
      (allocated exam-l-3)
      (allocated exam-l-4)
      (allocated exam-l-5)
      (allocated exam-s-1)
      (allocated exam-s-2)
      (allocated exam-s-3)
      (allocated exam-s-4)
      (allocated exam-s-5)
      (allocated exam-s-6)
      (allocated exam-s-7)
      (allocated exam-s-8)
      (allocated exam-s-9)
      (allocated exam-s-10)
    )
  )
)
